### ISSUE TITLE
Tvorba Katalógu požiadaviek

### ISSUE THREAD

**Issue by Krajcovic70** [TIS2024-FMFI/smelyzajko-gui#1]
- [x] Prvé stretnutie so zadávateľom
- [x] Tvorba úvodného draftu požiadaviek
- [ ] Dokončenie katalógu požiadaviek

**Comment by tibor-cernak** [comment]
Poslal som upravený draft KP na skontrolovanie. Čakáme na odpoveď.

**Comment by pavelpetrovic** [comment]
posledne pripomienky od zadavatela:
- vstup z klaves:
     moduly si z inicializacie mozu zaregistrovat callback na nejaku mnozinu shortcut klaves napr. CTRL-A  a CTRL-D
    (zmena v 2. casti: " ak nie je aktívny žiadny konkrétny vstupný prvok." => " ak ma focus lubovoľný jeden vstupný prvok, ak to použitý GUI framework dovolí".
- 3.7. prec slovo niektorych
- 3.8. mozu byt => budu
- 3.10  interagovať s rozhraním   => tato formulacia ma zmiatla
- 3.12.2 "Taktiež bude možné" => api umozni
sem este napisem komentare k ostatnym

**Comment by pavelpetrovic** [comment]
- v 3.14 mi skôr sedí požiada ako vyžiada
- navrhujem 3.18 prehodiť do 3.22 a urobiť z toho tretí mód - prehrávanie. 
  (následne poprehadzovať trochu tie požiadavky) 
  v prehrávacom móde sa predpokladá,
  že riadiaci systém robota nebeží a GUI "simuluje" predchádzajúci beh prevádzkového módu pre tie prvky, 
  pre ktoré bol vytvorený záznam. Jeden z parametrov inicializačnej funkcie modulu je režim.
  Ak sa modul inicializuje v konfiguračnom režime, vie, že nebude prevádzka, ale stále musí komunikovať
  s GUI do určitej miery - napr. oznámiť aké prvky poskytuje. Ak sa inicializuje v prehrávacom režime, 
  rovnako a je jeho úlohou zabezpečiť dáta z predchádzajúcej jazdy (ale od GUI dostane priečinok,
   do ktorého ich predtým zaznamenával). V prevádzkovom režime by sa mali zaznamenávať všetky 
   prvky, ktoré sa nachádzajú aspoň v jednej "aktívnej" šablóne, aby používateľ počas prehrávania 
   vedel ľubovoľne šablóny prepínať,
   tie prvky, ktoré nie sú v žiadnej, sa nemusia logovať. 
   Toto má ale dosť vážne dôsledky, čiže GUI manažér by mal volať  samostatný callback modulu pre logovanie.
   Jeden callback bude kresliť a druhý bude logovať. Asi bude stačiť pre grafické prvky, textové nech sa logujú
   ako vedia po svojom. Čiže ak je prvok viditeľný a logovaný, bude sa volať
      vykresli_sa(handle_na_canvas)
      zaloguj_sa()
   ak je viditelny, ale nie je logovany, zavola sa
      vykresli_sa(handle_na_canvas)
    a ak nie je viditelny, ale je logovany, zavola sa
       zaloguj_sa()
    ine mozno lepsie riesenie moze byt namiesto toho urobit jeden callback a to, ci sa kresli a loguje dat ako
      jeden parameter "action", co bude bitova maska obsahujuca dva atributy DO_PAINTING, DO_LOGGING, 
      ktore GUI manazer adekvatne nastavi. 
   toto je sice uz diskusia trochu o navrhu, ale v tomto projekte patri to rozhranie do specifikacie a toto je vec 
   rozhrania, takze to asi stale patri sem.
    Logovanie by mal mať na starosti sám každý modul, nie GUI manažér (asi by GUI manažér mohol poskytnúť 
    aspoň API na uloženie nejakého obázka v pamäti do súboru .PNG, ale to už veľmi záleží na tom, aký grafický 
    framework sa použije a ako celkovo funguje... takže to sem asi nepíšme, alebo iba ako voliteľnú požiadavku) 
- 3.19:  "Ak áno, systém pošle cestu k adresáru, kde sa majú potrebné údaje ukladať a taktiež maximálnu frekvenciu
ukladania."  - tieto dve položky (ktorý záznam a frekvencia) by si GUI manažér mal vypýtať od používateľa pri spustení.
  // už je požiadavka dosť kombinovaná, tak to prípadne rozbite na menšie, aby boli atomické
- v kontexte ostatných tu komentárov je 3.20 asi možné celkom odstrániť (ale najskôr to premyslite či áno),
   idea je že buď je prevádzka alebo je replay a keď je replay, tak sa iba "animuje" zo záznamu, pričom
   nemusí sa animovať všetko, ale iba to, čo bolo v prevádzke logované, ostatné prvky šablóny nebudú ukazovať nič
    (ak máte iný/lepší nápad/predstavu, prípadne skúste sformulovať nejak inak) 
- 3.21 by som asi prehodil niekam vyššie, napr. pred 3.16     
- 3.23.2. append(" do zvoleného súboru (save-as).")  
// zostáva nevyjasnená otázka ako bude systém vedieť medzi ktorými troma (napr. troma) šablónami 
// má prevádzkový mód prepínať - napr. pripravím si sedem rôznych šablón, ale teraz chcem používať 
// iba tri z nich - musím tie ostatné presunúť do iného priečinka a systém bude prepínať medzi všetkými, 
// ktoré nájde v nejakom priečinku? ok, dá sa s tým žiť, alebo iná možnosť, že niekde - napr. v tom konfigu, 
// keď ho už máme - bude zoznam šablón, ktoré majú byť použité, keď sa nabudúce spustí prevádzkový mód
// potom by bolo fajn mat možnosť poslať konfig ako command line parameter, čiže budem mať pripravených
// viac konfigov
- 3.24.2. Prevádzkový mód umožní používateľovi prepínať medzi šablónami pomocou klávesových 
skratiek => append(", alebo kliknutím na nenápadnú kontrolku niekde v GUI rozhraní.")      
  // to pre situácie, že GUI beží na tablete a klávesnica tam ani nie je
- 3.23.7. "Ďalšou" -> "Hlavnou"  // alebo nieco podobne
 a  "nastavenia veľkosti a polohy" => "nastavenia prítomnosti, veľkosti a polohy"    
    // teda nie vsetky dostupne prvky musia byt v kazdej sablone, da sa vybrat, ci tam prvok je, alebo nie je
- 3.24.3.  "3.7" => "3.10"

**Comment by tibor-cernak** [comment]
V komentári sa spomína "inicializácii modulu v režime", ale úplne nerozumieme prečo by sa mal modul inicializovať v rôznych režimoch? Nestačila by jedna inicializácia, kde modul poskytne svoje funkcie, prvky alebo prípadne premenné s možnými hodnotami? Nie je to zbytočná komplexita.

> V prevádzkovom režime by sa mali zaznamenávať všetky prvky, ktoré sa nachádzajú aspoň v jednej "aktívnej" šablóne, aby používateľ počas prehrávania vedel ľubovoľne šablóny prepínať

Máme to teda chápať, že v prevádzkovom režime sa majú zaznamenávať všetky možné prvky, ktoré su v šablóne? 
Nechceli sme to spraviť tak, že v konfiguračnom móde systému si použivateľ zvolí, ktoré prvky sa budú logovať? 


> 3.19: "Ak áno, systém pošle cestu k adresáru, kde sa majú potrebné údaje ukladať a taktiež maximálnu frekvenciu ukladania." - tieto dve položky (ktorý záznam a frekvencia) by si GUI manažér mal vypýtať od používateľa pri spustení.

Je už  v poriadku táto požiadavka?
- Pri inicializácii GUI prvku vie používaťeľ cez textový konfiguračný súbor alebo v konfiguračnom móde systému oznámiť, či sa výstup prvku bude logovať pre prípadné prehranie.  Vtedy si GUI manažér pri spustení vypýta od používateľa adresár pre záznam a frekvenciu. 

alebo po rozbití

- Pri inicializácii GUI prvku vie používaťeľ cez textový konfiguračný súbor alebo v konfiguračnom móde systému oznámiť, či sa výstup prvku bude logovať pre prípadné prehranie. 
- Pri logovaní výstupu prvkov pre prípadné prehranie si GUI manažer pri spustení vypýta od používateľa adresár pre záznam a frekvenciu


Taktiež sme sa bavili, že či je treba mať konfiguračný súbor pre GUI manažer. V požiadavkách sa spomína v bode:
- 3.4. GUI manažér načíta zoznam modulov z konfiguračného súboru

Ale keďže sme sa bavili, že moduly budu manuálne prilinkované a program sa bude zakaždým prekompilovávať, treba mať tento konfiguračný súbor? Ďalej je spomenutý v bode:
- 3.19. Pri inicializácii GUI prvku vie používateľ cez textový konfiguračný súbor alebo v konfiguračnom móde systému oznámiť

Tu tiež si úplne nevieme predstaviť, ako v tom konfiguračnom súbore sa bude spomínať nejaký modul a ešte k tomu prvok tohto modulu. Čo ak ten modul nebude prilikovaný? Pri zmene bude treba robiť zmeny na rôznych miestach. Nestačilo by v konfiguračnom móde systému žaškrtnúť checkbox ktorý bude znamenať, že sa výstup prvku má logovať?

Tým pádom potreba mať konfiguračný súbor padá. Aký je Váš názor na to? 


Ostatné poznámky sme zapracovali do KP, ktorý zašleme po vyriešení vyššie spomenutých bodov.

**Comment by tibor-cernak** [comment]
@pavelpetrovic Na mail sme poslali finálnu verziu KP na formálne odsúhlasenie.
