### ISSUE TITLE
Skúmanie a testovanie ImGui

### ISSUE THREAD

**Issue by Krajcovic70** [TIS2024-FMFI/smelyzajko-gui#10]

**Comment by zneupauer** [comment]
![Image](https://github.com/user-attachments/assets/9586f27c-4290-47bf-80d7-1759e6d3b099)

**Comment by zneupauer** [comment]
Moje poznatky: 
Najprv som mala problemy so set up(om). Akonahle ale bol set up hotovy, pracovalo sa s tym pomerne prijemne a intuitivne (c++ friendly).

- Umožňuje vytvárať GUI priamo v rámci renderovacieho cyklu aplikácie, čo je vhodné tam, kde je potrebné často a rýchlo meniť prvky na obrazovke.
- ImGui je ľahký a má malú pamäťovú stopu, čo ho robí veľmi rýchlym a nenáročným na systémové zdroje. Qt je robustnejší a poskytuje viac funkcií, ale jeho zložitosť prináša vyššie nároky na výkon a pamäť.
- ImGui je jednoducho prenositeľný medzi rôznymi platformami a knižnicami. Stačí ho spojiť s backendom (napríklad OpenGL, DirectX) a nemusíte sa starať o závislosti, ktoré bývajú potrebné pri Qt. To môže byť výhodné pre aplikácie, ktoré bežia na vlastných enginoch alebo menej bežných platformách.
