### ISSUE TITLE
Vytvorenie posúvnika (slider) v konfiguračnom režime

### ISSUE THREAD

**Issue by tibor-cernak** [TIS2024-FMFI/smelyzajko-gui#25]

**Comment by tibor-cernak** [comment]
'Controls' okno sluzi zatial iba na debuggovanie, ukladanie tych widgetov sa bude robit inym sposobom. 
![image](https://github.com/user-attachments/assets/03db1fd8-9822-4845-bb4a-f32bb27228f3)

Zatial je postup na ukladanie slidera takyto:

1. Po kliknuti na tlacitko ktore pridava Slider vybehne nasledujuci popup:
![image](https://github.com/user-attachments/assets/e7eb6e8e-c2e8-4bbf-9786-a822ed812663)
Su tam default hodnoty.
2. Nasledne si user vie nastavit hodnoty.
![image](https://github.com/user-attachments/assets/58c479b6-0c30-4bdf-8cee-3127a02bbfc4)
3. User vie moznost pridania zrusit tlacitkom "Cancel" alebo pridat Slider tlacitkom "Add"
4. Pridany slider:
![image](https://github.com/user-attachments/assets/370004f1-4954-49c9-809a-c42f12bf5ddd)

**Comment by tibor-cernak** [comment]
Taktiez je mozne slider posuvat a menit sirku kliknutim a posuvanim cez cerveny handle:
![image](https://github.com/user-attachments/assets/ff3c28b4-a792-4d36-80f5-18dc3d2d7b14)
Tu je zmenena pozicia a sirka slidera:
![image](https://github.com/user-attachments/assets/504d54fa-24a1-4d49-bb68-3e6f212d516b)

**Comment by tibor-cernak** [comment]
Taktiez je vytvoreny slider pre integer. Postup je identicky:
![image](https://github.com/user-attachments/assets/dd53f740-17d1-48be-bd78-ccf4f5382c7d)

**Comment by tibor-cernak** [comment]
Len taka myslienka: mozno v buducnosti by sa mohla pridat moznost vytvorenia vertikalneho posuvnika.

**Comment by Krajcovic70** [comment]
Dost dobre spravene a myslienka s vertikalnym posuvnikom sa mi tiez paci

**Comment by zneupauer** [comment]
velmi prakticke je, ze sa da vybrat medzi int a float sliderom
